### ISSUE TITLE
Sci/Eng expansion to recognise more than one facility type

### ISSUE THREAD

**Issue by RustyDios** [WOTCStrategyOverhaul/LivingSpace#13]
The current count for when to add Scientist/Engineers to the crew count is based on one singular facility in LSHelpers.uc

I would like to see this expanded to a possible array of entries.

The use case is someone designs an alternative Lab/Workshop but it is possible to build this new facility and/or base game facilities. Both should make 'Staff' not count as 'Crew'
Or someone may be really struggling and might find relief from having either the ProvingGrounds OR Workshop built to not count Engineers as crew.

I wasn't sure if this should be raised as an issue, or a feature request but wanted to note the idea somewhere it wouldn't get lost.

**Comment by Xymanek** [comment]
I wanted to make it array-based from the start, but the problem is localization:

https://github.com/WOTCStrategyOverhaul/LivingSpace/blob/b511dfff607aba4cc7e5025eda7e7b22aa088677/LivingSpace/Localization/LivingSpace.int#L8-L10
