### ISSUE TITLE
Save compatibility with CI b2

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/LivingSpace#2]
Since we are extracting part of CI state into this mod, we should investigate how to "transfer" it from CI b2 saves

**Comment by cannonfodder1** [comment]
Is that really a big concern? B3 saves are going to be incompatible with B2 saves regardless

**Comment by Xymanek** [comment]
Oh, what is causing the incompat?

**Comment by cannonfodder1** [comment]
I kinda just assumed that it was going to be. The only incompat I know about specifically is that I deleted all the old activities in the epic activity rework, which means things will break if a B2 save is loaded and there are soldiers out doing activities. I could restore them for backwards compatibility though.

**Comment by Xymanek** [comment]
Ah right. Nah, just gonna declare b2 saves incompatible in that case
